from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from .crew_service import list_crew, load_crew_record
from .port_requirements import load_port_requirement


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _safe_name(s: str) -> str:
    return (
        (s or "")
        .strip()
        .lower()
        .replace(" ", "_")
        .replace("/", "_")
        .replace("\\", "_")
    )


def generate_crew_list_txt(portalis_root, state) -> str:
    crew_summary = list_crew(portalis_root)

    lines = []
    lines.append("PORTALIS MINI – CREW LIST")
    lines.append(f"Generated (UTC): {utc_now_iso()}")
    lines.append("-" * 72)
    lines.append(f"Vessel: {state.vessel.ship_name}")
    lines.append(f"IMO: {state.vessel.imo}")
    lines.append(f"Voyage No: {state.voyage.voyage_no}")
    lines.append(f"Arrival Port: {state.voyage.arrival_port}")
    lines.append("-" * 72)
    lines.append(f"{'No.':<4} {'Name':<30} {'Rank':<20} {'Crew ID':<12}")
    lines.append("-" * 72)

    for i, c in enumerate(crew_summary, start=1):
        lines.append(f"{i:<4} {c['name'][:30]:<30} {c['rank'][:20]:<20} {c['crew_id']:<12}")

    lines.append("-" * 72)
    lines.append(f"Total Crew: {len(crew_summary)}")
    return "\n".join(lines) + "\n"


def generate_health_declaration_txt(portalis_root, state) -> str:
    lines = []
    lines.append("PORTALIS MINI – MARITIME DECLARATION OF HEALTH (DRAFT)")
    lines.append(f"Generated (UTC): {utc_now_iso()}")
    lines.append("-" * 72)
    lines.append(f"Vessel: {state.vessel.ship_name}")
    lines.append(f"IMO: {state.vessel.imo}")
    lines.append(f"Call Sign: {state.vessel.call_sign}")
    lines.append(f"Flag: {state.vessel.flag}")
    lines.append("")
    lines.append(f"Departure Port: {state.voyage.departure_port}")
    lines.append(f"Arrival Port: {state.voyage.arrival_port}")
    lines.append(f"ETA: {state.voyage.eta}")
    lines.append("")
    lines.append("Health Status: ______________________________")
    lines.append("Master / Responsible Officer: ______________")
    lines.append("Remarks: __________________________________")
    lines.append("-" * 72)
    lines.append("This is a draft generated by Portalis Mini.")
    return "\n".join(lines) + "\n"


def generate_port_checklist_txt(portalis_root, state) -> str:
    port_name = (state.voyage.arrival_port or "").strip()
    port = load_port_requirement(portalis_root, port_name) if port_name else {
        "port_name": "",
        "country": "",
        "required_docs": [],
        "non_standard_forms": [],
        "certificate_requirements": [],
        "notes": "",
    }

    lines = []
    lines.append("PORTALIS MINI – PORT REQUIREMENT CHECKLIST")
    lines.append(f"Generated (UTC): {utc_now_iso()}")
    lines.append("-" * 72)
    lines.append(f"Vessel: {state.vessel.ship_name}")
    lines.append(f"Arrival Port: {port.get('port_name', port_name)}")
    lines.append(f"Country: {port.get('country', '')}")
    lines.append("-" * 72)

    lines.append("REQUIRED DOCUMENTS")
    if port.get("required_docs"):
        for x in port["required_docs"]:
            lines.append(f"[ ] {x}")
    else:
        lines.append("[ ] No required document list defined")

    lines.append("")
    lines.append("NON-STANDARD FORMS")
    if port.get("non_standard_forms"):
        for x in port["non_standard_forms"]:
            lines.append(f"[ ] {x}")
    else:
        lines.append("[ ] None listed")

    lines.append("")
    lines.append("CERTIFICATE REQUIREMENTS")
    if port.get("certificate_requirements"):
        for x in port["certificate_requirements"]:
            lines.append(f"[ ] {x}")
    else:
        lines.append("[ ] None listed")

    if port.get("notes"):
        lines.append("")
        lines.append("NOTES")
        lines.append(port["notes"])

    lines.append("-" * 72)
    return "\n".join(lines) + "\n"


def save_generated_text(portalis_root, category: str, filename: str, text: str) -> str:
    out_dir = Path(portalis_root) / "generated" / category
    out_dir.mkdir(parents=True, exist_ok=True)

    out_path = out_dir / filename
    out_path.write_text(text, encoding="utf-8")
    return str(out_path)