from __future__ import annotations

from pathlib import Path

from .crew_service import list_crew
from .port_requirements import load_port_requirement
from .storage import utc_now_iso


def _safe_name(value: str) -> str:
    return (
        (value or "")
        .strip()
        .lower()
        .replace(" ", "_")
        .replace("/", "_")
        .replace("\\", "_")
    )


def generate_crew_list_txt(portalis_root, state) -> str:
    crew_summary = list_crew(portalis_root)

    lines = [
        "PORTALIS MINI - CREW LIST",
        f"Generated (UTC): {utc_now_iso()}",
        "-" * 72,
        f"Vessel: {state.vessel.name}",
        f"IMO: {state.vessel.imo_number or ''}",
        f"Voyage No: {state.voyage.voyage_number}",
        f"Arrival Port: {state.voyage.arrival_port}",
        "-" * 72,
        f"{'No.':<4} {'Name':<30} {'Rank':<20} {'Crew ID':<12}",
        "-" * 72,
    ]

    for idx, crew in enumerate(crew_summary, start=1):
        rank = str(crew.get("rank") or "")
        name = str(crew.get("name") or "")
        lines.append(f"{idx:<4} {name[:30]:<30} {rank[:20]:<20} {crew['crew_id']:<12}")

    lines.append("-" * 72)
    lines.append(f"Total Crew: {len(crew_summary)}")
    return "\n".join(lines) + "\n"


def generate_health_declaration_txt(portalis_root, state) -> str:
    lines = [
        "PORTALIS MINI - MARITIME DECLARATION OF HEALTH (DRAFT)",
        f"Generated (UTC): {utc_now_iso()}",
        "-" * 72,
        f"Vessel: {state.vessel.name}",
        f"IMO: {state.vessel.imo_number or ''}",
        f"Call Sign: {state.vessel.call_sign or ''}",
        f"Flag: {state.vessel.flag_state or ''}",
        "",
        f"Departure Port: {state.voyage.departure_port}",
        f"Arrival Port: {state.voyage.arrival_port}",
        f"ETA: {state.voyage.eta}",
        "",
        "Health Status: ______________________________",
        "Master / Responsible Officer: ______________",
        "Remarks: __________________________________",
        "-" * 72,
        "This is a draft generated by Portalis Mini.",
    ]
    return "\n".join(lines) + "\n"


def generate_port_checklist_txt(portalis_root, state) -> str:
    port_name = (state.voyage.arrival_port or "").strip()
    port = load_port_requirement(portalis_root, port_name) if port_name else {
        "port_name": "",
        "country": "",
        "required_docs": [],
        "non_standard_forms": [],
        "certificate_requirements": [],
        "notes": "",
    }

    lines = [
        "PORTALIS MINI - PORT REQUIREMENT CHECKLIST",
        f"Generated (UTC): {utc_now_iso()}",
        "-" * 72,
        f"Vessel: {state.vessel.name}",
        f"Arrival Port: {port.get('port_name', port_name)}",
        f"Country: {port.get('country', '')}",
        "-" * 72,
        "REQUIRED DOCUMENTS",
    ]

    if port.get("required_docs"):
        lines.extend(f"[ ] {item}" for item in port["required_docs"])
    else:
        lines.append("[ ] No required document list defined")

    lines.append("")
    lines.append("NON-STANDARD FORMS")
    if port.get("non_standard_forms"):
        lines.extend(f"[ ] {item}" for item in port["non_standard_forms"])
    else:
        lines.append("[ ] None listed")

    lines.append("")
    lines.append("CERTIFICATE REQUIREMENTS")
    if port.get("certificate_requirements"):
        lines.extend(f"[ ] {item}" for item in port["certificate_requirements"])
    else:
        lines.append("[ ] None listed")

    if port.get("notes"):
        lines.extend(["", "NOTES", port["notes"]])

    lines.append("-" * 72)
    return "\n".join(lines) + "\n"


def save_generated_text(portalis_root, category: str, filename: str, text: str) -> str:
    out_dir = Path(portalis_root) / "generated" / _safe_name(category)
    out_dir.mkdir(parents=True, exist_ok=True)

    out_path = out_dir / filename
    out_path.write_text(text, encoding="utf-8")
    return str(out_path)
