from __future__ import annotations

LINE_BASIC = 0x914E5A7D
LINE_REPEATED = 0x2A7495F1
TEXT_BASIC = 0xBC849C9A
VERTEX_ADDED = 0x3E512D3A
AREA_BASIC = 0x4A0B27F6
POINT_BASIC = 0x4B902E56


FAMILY_CONSTANTS: dict[str, int] = {
    "LINE_BASIC": LINE_BASIC,
    "LINE_REPEATED": LINE_REPEATED,
    "TEXT_BASIC": TEXT_BASIC,
    "VERTEX_ADDED": VERTEX_ADDED,
    "AREA_BASIC": AREA_BASIC,
    "POINT_BASIC": POINT_BASIC,
}
