from __future__ import annotations

from .models import SightInput, SkyfieldResult
from .lop import LOPResult


def render_nsc02_lop_txt(
    *,
    form: str,   # "NSC-02"
    generated_utc: str,
    s: SightInput,
    sky: SkyfieldResult,
    res: LOPResult,
    computed_by: str = "",
    checked_by: str = "",
) -> str:
    lines: list[str] = []
    lines.append("NAVSYS MINI – LINE OF POSITION")
    lines.append(f"FORM: {form}")
    lines.append(f"Generated (UTC): {generated_utc}")
    lines.append("-" * 72)

    lines.append("INPUTS")
    lines.append(f"Time (UTC): {s.time_utc}")
    lines.append(f"Position: {s.lat:.6f}, {s.lon:.6f}")
    lines.append(f"Body: {s.body_kind} / {s.body_name}")
    lines.append(f"Observed Altitude (Ho): {s.observed_ho_deg:.2f}°")

    lines.append("")
    lines.append("SKYFIELD RESULT")
    lines.append(f"True Azimuth (Zn): {sky.zn_deg:.2f}°")
    lines.append(f"Computed Altitude (Hc): {sky.hc_deg:.2f}°")

    lines.append("")
    lines.append("STEP-BY-STEP")
    lines.append(f"1. Ho = {res.ho_deg:.2f}°")
    lines.append(f"2. Hc = {res.hc_deg:.2f}°")
    lines.append("3. Intercept a = (Ho - Hc) × 60")
    lines.append(
        f"4. a = ({res.ho_deg:.2f}° - {res.hc_deg:.2f}°) × 60 = {res.intercept_nm:.2f} NM"
    )
    lines.append(f"5. Direction = {res.towards_away}")
    lines.append(f"6. Zn = {res.zn_deg:.2f}°")
    lines.append(
        f"7. LOP courses = {res.lop_course_1_deg:.2f}° / {res.lop_course_2_deg:.2f}°"
    )

    lines.append("")
    lines.append("RESULT")
    lines.append(f"Intercept: {res.intercept_nm:.2f} NM {res.towards_away}")
    lines.append(f"LOP orientation: {res.lop_course_1_deg:.2f}° / {res.lop_course_2_deg:.2f}°")

    lines.append("")
    lines.append("SIGNATURES")
    lines.append(f"Computed by: {computed_by or '________________'}")
    lines.append(f"Checked by:  {checked_by or '________________'}")
    lines.append("-" * 72)
    lines.append(f"Generated by NAVSYS Mini | Form {form}")

    return "\n".join(lines) + "\n"