from __future__ import annotations

from .models import SightInput, SkyfieldResult
from .compass_error import CompassErrorResult


def _fmt_signed_dir(value: float | None) -> str:
    if value is None:
        return ""
    if value > 0:
        return f"{abs(value):.2f}° E"
    if value < 0:
        return f"{abs(value):.2f}° W"
    return "0.00°"


def render_nsc01_compass_error_txt(
    *,
    form: str,   # "NSC-01"
    generated_utc: str,
    s: SightInput,
    sky: SkyfieldResult,
    res: CompassErrorResult,
    computed_by: str = "",
    checked_by: str = "",
) -> str:
    mode = res.instrument_mode
    label = res.instrument_label

    lines: list[str] = []
    lines.append("NAVSYS MINI – COMPASS / GYRO ERROR")
    lines.append(f"FORM: {form}")
    lines.append(f"Generated (UTC): {generated_utc}")
    lines.append("-" * 72)

    lines.append("INPUTS")
    lines.append(f"Time (UTC): {s.time_utc}")
    lines.append(f"Position: {s.lat:.6f}, {s.lon:.6f}")
    lines.append(f"Body: {s.body_kind} / {s.body_name}")
    lines.append(f"Instrument Mode: {mode}")
    lines.append(f"Instrument Label: {label}")
    lines.append(f"Observed Bearing: {s.observed_bearing_deg:.2f}°")

    if s.variation_deg is not None:
        lines.append(f"Variation: {_fmt_signed_dir(s.variation_deg)}")

    lines.append("")
    lines.append("SKYFIELD RESULT")
    lines.append(f"True Azimuth (Zn): {sky.zn_deg:.2f}°")
    if sky.hc_deg is not None:
        lines.append(f"Computed Altitude (Hc): {sky.hc_deg:.2f}°")

    lines.append("")
    lines.append("STEP-BY-STEP")
    lines.append(f"1. True Azimuth (Zn) = {res.true_azimuth_deg:.2f}°")
    lines.append(f"2. Observed Bearing  = {res.bearing_used_deg:.2f}°")
    lines.append("3. Error = Zn - Bearing")
    lines.append(
        f"4. Error = {res.true_azimuth_deg:.2f}° - {res.bearing_used_deg:.2f}° = {res.error_deg:.2f}° {res.error_dir}"
    )

    if mode == "MAGNETIC":
        lines.append("")
        lines.append("MAGNETIC ANALYSIS")
        lines.append(f"Compass Error: {res.error_deg:.2f}° {res.error_dir}")

        if res.variation_deg is not None:
            lines.append(f"Variation: {_fmt_signed_dir(res.variation_deg)}")

        if res.observed_deviation_deg is not None:
            lines.append(f"Observed Deviation: {_fmt_signed_dir(res.observed_deviation_deg)}")

        if res.card_deviation_deg is not None:
            lines.append(f"Card Deviation: {_fmt_signed_dir(res.card_deviation_deg)}")

        if res.deviation_diff_deg is not None:
            lines.append(f"Difference from Card: {_fmt_signed_dir(res.deviation_diff_deg)}")

    lines.append("")
    lines.append("RESULT")
    if mode == "GYRO_1":
        lines.append(f"Gyro 1 Error: {res.error_deg:.2f}° {res.error_dir}")
    elif mode == "GYRO_2":
        lines.append(f"Gyro 2 Error: {res.error_deg:.2f}° {res.error_dir}")
    elif mode == "MAGNETIC":
        lines.append(f"Compass Error: {res.error_deg:.2f}° {res.error_dir}")
    else:
        lines.append(f"Bearing Error: {res.error_deg:.2f}° {res.error_dir}")

    lines.append("")
    lines.append("SIGNATURES")
    lines.append(f"Computed by: {computed_by or '________________'}")
    lines.append(f"Checked by:  {checked_by or '________________'}")
    lines.append("-" * 72)
    lines.append(f"Generated by NAVSYS Mini | Form {form}")

    return "\n".join(lines) + "\n"