from __future__ import annotations

from pathlib import Path
from typing import List

from .register_ns01 import NS01Row


def render_ns01_txt(
    *,
    rows: List[NS01Row],
    run_id: str,
    generated_utc: str,
    operator_name: str,
    vessel_name: str,
) -> str:
    """
    Printable NS-01 register.

    Must include:
    - FORM: NS-01
    - Run ID, UTC timestamp
    - Simple table
    - Footer line
    """
    # Column widths (tuned for readability on A4 print)
    cols = [
        ("Seq", 4),
        ("NAVAREA", 6),
        ("Warning_ID", 22),
        ("Type", 6),
        ("PSN", 23),
        ("Dist", 7),
        ("Band", 6),
        ("Plt", 4),
        ("Src", 8),
        ("Status", 6),
    ]

    def fmt_row(items):
        out = []
        for (val, (_, w)) in zip(items, cols):
            s = str(val)
            if len(s) > w:
                s = s[: w - 1] + "…"
            out.append(s.ljust(w))
        return " ".join(out).rstrip()

    header = []
    header.append("NAVSYS MINI – NAVWARN REGISTER")
    header.append("FORM: NS-01")
    header.append(f"Run ID: {run_id}")
    header.append(f"Generated (UTC): {generated_utc}")
    header.append(f"Vessel: {vessel_name or '__________'}")
    header.append(f"Operator: {operator_name or '__________'}")
    header.append("-" * 96)

    table = []
    table.append(fmt_row([c[0] for c in cols]))
    table.append("-" * 96)

    for r in rows:
        psn = f"{r.psn_lat:.5f}, {r.psn_lon:.5f}"
        dist = "" if r.dist_nm is None else f"{r.dist_nm:.1f}"
        table.append(
            fmt_row([
                r.seq,
                r.navarea,
                r.warning_id,
                r.type,
                psn,
                dist,
                r.band,
                "Y" if r.plotted == "YES" else "N",
                r.source_kind,
                r.status,
            ])
        )

    footer = []
    footer.append("-" * 96)
    footer.append("Generated by NAVSYS Mini v0.1 | Form NS-01")

    return "\n".join(header + table + footer) + "\n"


def write_text_file(text: str, path: str) -> None:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding="utf-8")